blooddonors/blooddonors/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.views.generic.base import TemplateView # new

#path('', include("ibd.urls")),
#path('', include('django.contrib.auth.urls'))
#path('', TemplateView.as_view(template_name='home.html'), name='home'),  # new
#path('accounts/', include('django.contrib.auth.urls')),

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ibd.urls")),
    #path('/', include('django.contrib.auth.urls')),
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),  # new


]

blooddonors/ibd/urls.py
from django.urls import path , include
from . import views
from django.views.generic.base import TemplateView # new


app_name = 'ibd'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('', TemplateView.as_view(template_name='ibd/index.html'), name='index'),  # new
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('donorlist/', views.DonorList.as_view()),
    path('donordetail/<pk>/', views.DonorDetail.as_view()),
    path('adddonor/', views.AddDonor.as_view()),
    path('updatedonor/<pk>/', views.UpdateDonor.as_view()),
    path('login/', views.login, name='login'),
    path('unsubscribe/', views.unsubscribe, name='unsubscribe'),
    path('forgetpwd/', views.forgetpwd, name='forgetpwd'),
    path('poster/', views.poster, name='poster'),
    path('privacypolicy/', views.privacypolicy, name='privacypolicy'),
    path('welcome/', views.welcome, name='welcome'),
    path('register/', views.register, name='register'),
    path('registersucess/', views.registersucess, name='registersucess'),
    path('note/', views.note, name='note'),
    path('thankyou/', views.thankyou, name='thankyou'),
    path('update_profile/<int:pk>/', views.update_profile, name='update_profile'),
    path('updatesucess/<int:pk>/', views.updatesucess, name='updatesucess'),
    path('user_history/<int:pk>/', views.user_history, name='user_history'),
    path('chng_pwd/<int:pk>/', views.chng_pwd, name='chng_pwd'),
    path('pwdchangesucess/<int:pk>/', views.pwdchangesucess, name='pwdchangesucess'),
    path('notmatch/', views.notmatch, name='notmatch'),
    path('logout/', views.logout, name='logout'),
    path('inthenews/', views.inthenews, name='inthenews'),
    path('donorsfaqs/', views.donorsfaqs, name='donorsfaqs'),

]

blooddonors/ibd/models.py
from datetime import datetime

from django.db import models
from datetime import datetime
from django.urls import reverse

# Create your models here.
class Donor(models.Model):
    donor_name = models.CharField(max_length=100,default='', blank=True)
    blood_group_choices = (
        ('A +ve', 'A +ve'),
        ('A -ve', 'A -ve'),
        ('B +ve', 'B +ve'),
        ('B -ve', 'B -ve'),
        ('AB +ve', 'AB +ve'),
        ('AB -ve', 'A -ve'),
        ('A1 +ve', 'A1 +ve'),
        ('A1 -ve', 'A1 -ve'),
        ('A2 +ve', 'A2 +ve'),
        ('A2 -ve', 'A2 -ve'),
        ('A1B +ve', 'A1B +ve'),
        ('A1B -ve"', 'A1B -ve"'),
        ('A2B +ve', 'A2B +ve'),
        ('A2B -ve"', 'A2B -ve"'),
        ('O +ve', 'O +ve'),
        ('O -ve', 'O -ve'),
    )
    blood_group = models.CharField(max_length=10,choices=blood_group_choices,default= " ")
    donor_std  = models.CharField(max_length=3)
    donor_zip  = models.CharField(max_length=6)
    donor_phone = models.CharField(max_length=10)
    donor_email = models.EmailField(unique= True,max_length=254)
    donor_pass = models.CharField(max_length=20)

    def __str__(self):
        return  self.donor_name


class DonorHistory(models.Model):
    req_phone = models.CharField(max_length=10)
    req_reply = models.CharField(max_length=50)
    req_date = models.DateTimeField(default=datetime.now, blank=True)
    donors_hist = models.ForeignKey(Donor,on_delete= models.CASCADE)

    def __str__(self):
        return self.req_phone

    class Meta:
        ordering = ['req_phone']

blooddonors/ibd/forms.py
from django import  forms
from .models import  Donor , DonorHistory



class  DonorForm(forms.ModelForm):
    class Meta:
        model = Donor
        labels = {
            'donor_name'  : '*Full Name',
            'blood_group' : '*Blood Group',
            'donor_std'   : '* STD Code',
            'donor_zip'   : 'Postal Pincode',
            'donor_phone' : '* Mobile Number',
            'donor_email' : '* Email Address'

        }
        fields = "__all__"

blooddonors/ibd/views.py
from django.shortcuts import render , redirect ,get_object_or_404
from django.http import HttpResponse

from .forms import DonorForm
from .models import Donor, DonorHistory
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.contrib.auth.models import  User
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.
# Create your views here.
from django.views.generic import ListView , UpdateView , CreateView ,DetailView


#ddef home(request):
#    return render(request, 'home.html')

def index(request):
    if request.session.has_key('donor_email'):
        return render(request, 'index.html')

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

def register(request):
    if request.method == 'POST':
        form = DonorForm(request.POST)
        if form.is_valid():
            return HttpResponse("hello")
        else:
            return HttpResponse("hi")
    else:
        return HttpResponse("hi")
        #return HttpResponse("hello")
        #return render(request, 'ibd/register.html')


def registersucess(request):
    if request.method == 'POST':
        donor_name = request.POST['Full_Name']
        blood_group = request.POST['Blood_Group']
        donor_std = request.POST['stdcode_id']
        donor_zip = request.POST['Pincode']
        donor_phone = request.POST['Mobile_Number']
        donor_email = request.POST['Email']
        donor_pass = request.POST['pwd']
        Donor.objects.create(donor_name=donor_name, blood_group=blood_group, donor_std=donor_std, donor_zip=donor_zip,
                             donor_phone=donor_phone, donor_email=donor_email,donor_pass=donor_pass)
        return render(request, 'ibd/registersuccess.html')
    else:
        error = 'Something went wrong'
    return render(request, 'ibd/index.html')

def detail(request, donor_id):
    donor = get_object_or_404(Donor, pk=donor_id)
    return render(request, 'ibd/detail.html', {'donor': donor})

class DonorList(ListView):
    model = Donor

class DonorDetail(DetailView):
    model = Donor

class UpdateDonor(UpdateView):
    model = Donor
    fields = ['donor_name','blood_group','donor_std','donor_zip','donor_phone','donor_email']
    success_url = '/'

class AddDonor(CreateView):
    model = Donor
    template_name = 'ibd/register.html'
    fields = ['donor_name','blood_group','donor_std','donor_zip','donor_phone','donor_email']
    success_url = '/'

def welcome (request):

    if request.session.has_key('donor_email'):
        donor_email = request.session['donor_email']
        d = get_object_or_404(Donor, donor_email=donor_email)
        donor = get_object_or_404(Donor, pk=d.id)
        return render(request, 'ibd/welcome.html', {'donor': donor})
    else:
        if request.method == 'POST':
            donor_email = request.POST['mobilenumber']
            donor_pass = request.POST['password']
            request.session['donor_email'] = donor_email
            try:
                d = get_object_or_404(Donor, donor_email=donor_email,donor_pass=donor_pass)
            except:
                return render(request, 'ibd/notfound.html')
            donor = get_object_or_404(Donor, pk=d.id)
            return render(request, 'ibd/welcome.html', {'donor': donor})

        else:
            error = 'Something went wrong'
        return render(request,'ibd/index.html')

def unsubscribe(request):
    return render(request, 'ibd/unsubscribe.html')

def forgetpwd(request):
    return render(request, 'ibd/forgetpwd.html')

def poster(request):
    return render(request, 'ibd/poster.html')

def privacypolicy(request):
    return render(request, 'ibd/privacypolicy.html')

def index(request):
    return render(request, 'ibd/index.html')

def thankyou(request):
    donor_phone = request.POST['txtno']
    donor_pass = request.POST['txtpwd']
    try:
         get_object_or_404(Donor, donor_phone=donor_phone,donor_pass=donor_pass)
    except:
        return render(request, 'ibd/notfound.html')
    Donor.objects.filter(donor_phone=donor_phone,donor_pass=donor_pass).delete()
    return render(request, 'ibd/thankyou.html')

def note(request):
    return render(request, 'ibd/note.html')

def update_profile(request,pk):
    donor = get_object_or_404(Donor, pk=pk)
    return render(request, 'ibd/update_profile.html', {"donor": donor})

def updatesucess(request,pk):
    if request.method == 'POST':
        donor_name = request.POST['Full_Name']
        blood_group = request.POST['Blood_Group']
        donor_std = request.POST['stdcode_id']
        donor_zip = request.POST['Pincode']
        donor_phone = request.POST['Mobile_Number']
        donor_email = request.POST['Email']
        try:
            d =  get_object_or_404(Donor, id=pk)
        except:
            return render(request, 'ibd/notfound.html')
        Donor.objects.filter(pk=d.id).update(donor_name=donor_name,blood_group=blood_group,donor_std=donor_std,donor_zip=donor_zip,donor_phone=donor_phone,donor_email=donor_email)
        return render(request, 'ibd/updatesuccess.html')
    else:
        error = 'Something went wrong'
        return render(request,'ibd/update_profile.html')

def chng_pwd(request,pk):
    donor = get_object_or_404(Donor, pk=pk)
    return render(request, 'ibd/chng_pwd.html', {"donor": donor})

def pwdchangesucess(request,pk):
    npwd = request.POST['npwd']
    cpwd = request.POST['cpwd']

    try:
        d = get_object_or_404(Donor, id=pk)
    except:
        return render(request, 'ibd/notfound.html')
    if npwd == cpwd :
        Donor.objects.filter(pk=d.id).update(donor_pass = npwd)
        return render(request, 'ibd/pwdchangesucess.html')
    else:
        return render(request, 'ibd/notmatch.html')


def user_history(request,pk):
    donor = get_object_or_404(Donor, pk=pk)
    result = DonorHistory.objects.filter(donors_hist=donor.id)
    context = {'donor':donor,'result':result}
    return  render(request, 'ibd/user_history.html', context)


def notmatch(request):
    return render(request, 'ibd/notmatch.html')

def inthenews(request):
    return render(request, 'ibd/inthenews.html')

def donorsfaqs(request):
    return render(request, 'ibd/donorsfaqs.html')

def login(request):
    return render(request, 'ibd/login.html')

def logout(request):
    try:
        del request.session['donor_email']
    except KeyError:
        pass

    return render(request, 'ibd/logout.html')

blooddonors/ibd/templates/ibd/donor_detail.html
<h1>Donor Details</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action>
    Name          :  {{ donor.donor_name }}<p>
    donor_email   :  {{ donor.donor_email }}<p>
</form>

blooddonors/ibd/templates/ibd/donor_form.html
<h2>Add New Donor</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p  }}
    <button type="submit" class="save btn btn-default">Add</button>
</form>

blooddonors/ibd/templates/ibd/inthenews.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Platelet Donors</title>
    <link href="http://www.indianblooddonors.com/images/fav.png" rel="shortcut icon">
    <!-- Bootstrap -->
    <link href="http://www.indianblooddonors.com/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://www.indianblooddonors.com/fonts/css/font-awesome.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    <link href="http://www.indianblooddonors.com/css/mystyle.css" rel="stylesheet">
    <link rel="stylesheet" href="http://www.indianblooddonors.com/styles.css">
    <script src="https://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <script src="http://www.indianblooddonors.com/script.js"></script>
    <script src="http://www.indianblooddonors.com/js/crawler.js" type="text/javascript"></script>
</head>
<body>
    <div class="container-fluid bg">
        <div class="container shadow bg1">


<div class="row topbg">
    <div class="col-md-6"> Blood Helpline Call: 07966772379</div>
    <div class="col-md-6" align="right"> Download our Apps to Contact Donors </div>
</div>
<div class="row">
    <div class="col-md-6">
        <img src="http://www.indianblooddonors.com/images/logo.png" class="img-responsive" alt="" />
    </div>
    <div class="col-md-6" align="right">
        <ul class="list-inline" style="padding-top:25px">
            <li><a href="#" target="_blank"><i class="fa fa-apple fa-2x" style="color:#000"></i></a></li>
            <li><a href="https://play.google.com/store/apps/details?id=com.ibd.plateletdonorapp" target="_blank"><i class="fa fa-android fa-2x" style="color:#090"></i></a></li>

        </ul>
    </div>
</div>

<div class="row menubg">

    <nav class="navbar navbar-inverse" style="margin-bottom:10px;">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class= ><a href='/'>Home</a></li>
                    <li class=><a href="{% url 'ibd:login' %}">Donors Login</a></li>
                    <li class=><a href="{% url 'ibd:forgetpwd' %}">Forgot Password</a></li>
                    <li class=><a href="{% url 'ibd:unsubscribe' %}">Unsubscribe</a></li>
                    <li class=active><a href="{% url 'ibd:inthenews' %}">In the News</a></li>
                    <li class=><a href="{% url 'ibd:poster' %}">Paste our Posters</a></li>
                    <li class=><a href="{% url 'ibd:donorsfaqs' %}">Donors FAQs</a></li>
                    <li><a href='https://www.facebook.com/Plateletdonors'>Facebook</a></li>

                </ul>

            </div>
        </div>
    </nav>

</div>

            <div class="row sliderbg mh-600" style="margin-top:-20px;">
                <div class="col-md-12">


                    <div class="list-group">
                        <a href="#" class="list-group-item active lst">
                            In The News
</a>
                        <a href="http://www.newindianexpress.com/lifestyle/health/2014/aug/17/Connecting-the-Missing-Blood-Dots-648763.html" class="list-group-item" style="color:blue;">1. Connecting the Missing Blood Dots - The Hindu</a>
                        <a href="HIRWAD14.php" class="list-group-item" style="color:blue;">2. Just send an SMS and get Platelets - Hitavada</a>
                        <a href="1455898_578505695536173_2137744163_n.php" class="list-group-item" style="color:blue;">3. Compassion runs in the veins of Poachas - Times of India</a>
                        <a href="https://www.youtube.com/watch?v=SSqyznFNqCI" class="list-group-item" style="color:blue;">4. You Only Need Passion to do Good Work - TedxNagpur</a>
                        <a href="http://social.yourstory.in/2013/06/creating-blood-relations-literally-through-their-ventures/" class="list-group-item" style="color:blue;">5. Creating blood relations, literally, through their ventures - Yourstory.in</a>
                        <a href="http://www.mid-day.com/lifestyle/2012/nov/261112-Mumbai-Guide-The-bloody-truth-Platelets-save-lives.htm" class="list-group-item" style="color:blue;">6. The Blood Truth - Platelets Save Lives - Midday Mumbai</a>
                        <a href="http://www.ehitavada.com/news.detail/paper_type/13/news_id/173888/date/2012-11-25" class="list-group-item" style="color:blue;">7. Saving Lives at the cost of an SMS - The Hitavada Nagpur</a>
                        <a href="TOI.php" class="list-group-item" style="color:blue;">8. Poachas now step up to Platelets- Times of India Nagpur</a>
                    </div>

                </div>
            </div>


<div class="row ftopbg" style="line-height:1.8; text-align:justify; color:#ABADAE">
    <div class="col-md-3">
        <p style="font-size:16px; color:#ccc"><strong>TECHNOLOGY PARTNERS</strong></p>
        <p> <a href="https://awaaz.de/" target="_blank">Awaaz De</a></p>
        <p> <a href="https://www.givingtuesdayindia.org/" target="_blank">Giving Tuesday India</a></p>
        <p> <a href="http://proso.io?ref=pd" target="_blank">Proso.io</a></p>
    </div>
    <div class="col-md-3">
        <p style="font-size:16px; color:#ccc"><strong>CONNECTIONS MADE</strong></p>
        <p> 1720 Platelet Donors Registered</p>
        <p> 17553 Requests served till date</p>
        <p> 262 Searches in Last 30 Days</p>
    </div>
    <div class="col-md-3">
        <p style="font-size:16px; color:#ccc"><strong>OUR OTHER INITIATIVES</strong></p>

        <p><a target="_blank" href='http://indianblooddonors.com/'>Indian Blood Donors</a></p>
        <p><a target="_blank" href="https://play.google.com/store/apps/details?id=com.appsthentic.sevakitchen">Seva Kitchen Food Sharing App</a></p>
    </div>
    <div class="col-md-3">
        <p style="font-size:16px; color:#ccc"><strong>CONTACT US</strong></p>
        <p><strong>Address:</strong></p>
        <p>
            Platelet Donors <br>
            127, New Colony,<br>
            Nagpur - 440001,<br>
            Maharashtra (India).
        </p>
        <p><strong>Email-id:</strong>info@plateletdonors.org</p>
    </div>
</div>
<div class="row fbottompbg" style="color:#666">
    <div class="col-md-6"> @ 2018 Plateletdonors.org. All right reserved. </div>
    <div class="col-md-6" align="right"> </div>
</div>
        </div>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <script>
            function validate(e) {
                //getting key code of pressed key
                var keycode = (e.which) ? e.which : e.keyCode;
                //var phn = document.getElementById('textarea');
                //
                //comparing pressed keycodes
                if ((keycode < 48 || keycode > 57) && keycode !== 13 && keycode !== 8 && keycode !== 46 && keycode !== 37 && keycode !== 39) {
                    e.preventDefault();
                    console.log("FAIL");
                    return false;
                } else {
                    console.log("OK!");
                }
            }
    </script>
</body>
<!-- Mirrored from indianblooddonors.com/privacypolicy.php by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 14 Mar 2018 05:06:16 GMT -->
</html>

blooddonors/ibd/templates/ibd/welcome.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Indian Blood Donors</title>
        <link href="http://www.indianblooddonors.com/images/fav.png" rel="shortcut icon">

        <!-- Bootstrap -->
        <link href="http://www.indianblooddonors.com/css/bootstrap.min.css" rel="stylesheet">

        <link href="http://www.indianblooddonors.com/fonts/css/font-awesome.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->

        <link href="http://www.indianblooddonors.com/css/mystyle.css" rel="stylesheet">
        <link rel="stylesheet" href="http://www.indianblooddonors.com/styles.css">
        <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
        <script src="http://www.indianblooddonors.com/script.js"></script>
        <script src="http://www.indianblooddonors.com/js/crawler.js" type="text/javascript"></script>
    </head>
    <body>
        <div class="container-fluid bg">
            <div class="container shadow bg1">
                <div class="row topbg">
                    <div class="col-md-6"> Need Blood? Call: 07966772377 </div>
                    <div class="col-md-6" align="right"> Download our Apps to Contact Donors </div>
                </div>
                <div class="row">
                    <div class="col-md-6"> <img src="http://www.indianblooddonors.com/images/logo.png" class="img-responsive"  alt=""/> </div>
                    <div class="col-md-6" align="right">
                        <ul class="list-inline" style="padding-top:25px">
                            <li><i class="fa fa-apple fa-2x" style="color:#000"></i></li>
                            <li><a href="https://play.google.com/store/apps/details?id=com.ibd.blooddonorapp&hl=en" target="_blank"><i class="fa fa-android fa-2x" style="color:#090"></i></a></li>
                            <li><i class="fa fa-windows fa-2x"  style="color:#39F"></i></li>
                        </ul>
                    </div>
                </div>

                <div class="row menubg">
                    <div class="col-md-12">
                        <div id='cssmenu'>
                            <ul>
                                <li  ><a  href='/index'>Home</a></li>
                                <li  class="active"><a href="{% url 'ibd:welcome' %}">My Profile</a></li>
                                <li ><a href="{% url 'ibd:unsubscribe' %}">Unsubscribe</a></li>
                                <li ><a href="{% url 'ibd:forgetpwd' %}">Forgot Password</a></li>
                                <li ><a href="{% url 'ibd:poster' %}">Paste our Posters</a></li>
                                <li><a href="{% url 'ibd:privacypolicy' %}">Privacy Policy</a></li>
                                <li><a href='https://www.facebook.com/IndianBloodDonors'>Facebook</a></li>
                            </ul>
                        </div>
                    </div>
                </div>


<div class="row sliderbg mh-600">
    <div class="col-md-4 col-sm-hidden col-xs-hidden pdr-30">
    </div>




              <table width="100%">
              <tr>
              <td width="17%" valign="top">
<div id="ddblueblockmenu" >
<ul>
    <li><a style="color: #ffffff" href="#">Welcome</a></li>
<li> <a style="color: #ffffff" href="{% url 'ibd:update_profile' pk=donor.pk %}">Update Profile</a></li>
<li><a style="color: #ffffff" href="{% url 'ibd:chng_pwd' pk=donor.pk %}">Change Password</a></li>
<!--<li><a style="color: #ffffff" href="removerqst.php" class="banner_link_text">Unsubscribe</a></li>-->
<li><a style="color: #ffffff" href="{% url 'ibd:user_history' pk=donor.pk  %}">Blood Donation History</a></li>
<li><a style="color: #ffffff" href="/logout">Logout</a></li>
</ul>

</div>
</td>
               <td width="83%" valign="top">
                   <table width="100%" border="1" style=" height: 300px">
                       <tr height="30" valign="top">
                     <td class=heading >welcome</td></tr>
                       <tr><td class="page_content1" valign="top"><p align="justify"><strong>Dear {{donor.donor_name}},</strong>
<br/>
<br/>
Thank you for Registering as a blood donor on Indianblooddonors.com .

<br/>
<br/>
We request you to Invite your Friends to  join this helpline. You also spread the word by Pasting our Poster
in your Office / College / Residential Complex / Hospitals / Blood Banks. Whenever you
go to a blood bank to donate blood please help create awareness about
the helpline.
<br/>
<br/>

Please check this space for further updates.
<br/>
<br/>
Warm Regards
<br/>
In Service
<br/>
<br/>
Khushroo & Fermin Poacha

                               </p>

        <p align="center"><font color="#0033FF"><strong></strong></font></p></td></tr>



                   </table>
               </td></tr>


              </table>





        <br/>

      <div class="clearfix"></div>
      <div class="col-md-12" style=" margin-top:10px">


        </div>


    </div>


<div class="row ftopbg" style="line-height:1.8; text-align:justify; color:#ABADAE">
                    <div class="col-md-3">
                        <p style="font-size:16px; color:#ccc"><strong>TECHNOLOGY PARTNERS</strong></p>
                        <p> <a href="https://www.awaaz.de/" target="_blank">Awaaz De</a></p>

                    </div>
                    <div class="col-md-3">
                        <p style="font-size:16px; color:#ccc"><strong>CONNECTIONS MADE</strong></p>

                        <p>12438 Blood Donors Registered</p>
                        <p>151695 Request Served Till Date</p>
                        <p>714 Connections made in last 30 Days</p>
                        <p>3 Donors Consented to Donate</p>
                        <p>4 Donors Refused to Donate</p>

                    </div>
                    <div class="col-md-3">
                        <p style="font-size:16px; color:#ccc"><strong>OUR OTHER INITIATIVES</strong></p>
                        <!--<p>Privacy Policy</p>
                        <p> Terms &amp; Conditions</p>
                        <p> Disclaimer</p>
                        <p> Cancellation &amp; Refund</p>
                        <p> Others</p>
                        --><p><a target="_blank" href='http://Plateletdonors.org'>Platelet Donors</a></p>
                        <p><a target="_blank" href="http://www.sevakitchen.org">Seva Kitchen</a></p>

                    </div>
                    <div class="col-md-3">
                        <p style="font-size:16px; color:#ccc"><strong>CONTACT US</strong></p>
                        <p><strong>Address:</strong></p>
                        <p> Indian Blood Donors <br>
                            127, New Colony,<br>
                            Nagpur - 440001,<br>
                            Maharashtra (India). </p>
                        <p><strong>Email-id:</strong> info@indianblooddonors.com</p>
                    </div>
                </div>
                <div class="row fbottompbg" style="color:#666">
                    <div class="col-md-6"> &copy 2020  Indian Blood Donors. All right reserved. </div>
                    <div class="col-md-6" align="right"> </div>
                </div>
            </div>
        </div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="js/bootstrap.min.js"></script>
        <script>
            function validate(e) {
                //getting key code of pressed key
                var keycode = (e.which) ? e.which : e.keyCode;
                //var phn = document.getElementById('textarea');
                //
                //comparing pressed keycodes
                if ((keycode < 48 || keycode > 57) && keycode !== 13 && keycode !== 8 && keycode !== 46 && keycode !== 37 && keycode !== 39) {
                    e.preventDefault();
                    console.log("FAIL");
                    return false;
                } else {
                    console.log("OK!");
                }
            }
        </script>
    </body>
</html>